-- KWhyzor Supabase database
-- Run this in Supabase SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  display_name text,
  avatar_url text,
  phone text,
  location text,
  plan text not null default 'Free' check (plan in ('Free','Pro','Business')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists display_name text;
alter table public.profiles add column if not exists avatar_url text;
alter table public.profiles add column if not exists phone text;
alter table public.profiles add column if not exists location text;
alter table public.profiles add column if not exists plan text not null default 'Free';
alter table public.profiles add column if not exists updated_at timestamptz not null default now();

create table if not exists public.bills (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  billing_date date not null default current_date,
  amount numeric(12,2) not null check (amount >= 0),
  units_kwh numeric(12,3) not null check (units_kwh >= 0),
  previous_units_kwh numeric(12,3),
  ocr_status text default 'manual',
  created_at timestamptz not null default now()
);

create table if not exists public.appliances (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  category text,
  wattage numeric(10,2) not null check (wattage >= 0),
  quantity integer not null default 1 check (quantity > 0),
  hours_per_day numeric(5,2) not null default 1 check (hours_per_day between 0 and 24),
  days_per_month integer not null default 30 check (days_per_month between 1 and 31),
  created_at timestamptz not null default now()
);

create table if not exists public.energy_reports (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text, energy_score integer check (energy_score between 0 and 100),
  estimated_consumption_kwh numeric(12,3), estimated_cost numeric(12,2),
  saving_opportunity numeric(12,2), ai_summary text,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.bills enable row level security;
alter table public.appliances enable row level security;
alter table public.energy_reports enable row level security;

drop policy if exists "profiles own rows" on public.profiles;
create policy "profiles own rows" on public.profiles for all using (auth.uid()=id) with check (auth.uid()=id);
drop policy if exists "bills own rows" on public.bills;
create policy "bills own rows" on public.bills for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
drop policy if exists "appliances own rows" on public.appliances;
create policy "appliances own rows" on public.appliances for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
drop policy if exists "reports own rows" on public.energy_reports;
create policy "reports own rows" on public.energy_reports for all using (auth.uid()=user_id) with check (auth.uid()=user_id);

-- Private avatar storage. Upload paths must start with the authenticated user's id.
insert into storage.buckets (id, name, public) values ('avatars', 'avatars', false) on conflict (id) do nothing;
drop policy if exists "avatar owner read" on storage.objects;
create policy "avatar owner read" on storage.objects for select to authenticated using (bucket_id='avatars' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists "avatar owner upload" on storage.objects;
create policy "avatar owner upload" on storage.objects for insert to authenticated with check (bucket_id='avatars' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists "avatar owner update" on storage.objects;
create policy "avatar owner update" on storage.objects for update to authenticated using (bucket_id='avatars' and (storage.foldername(name))[1]=auth.uid()::text) with check (bucket_id='avatars' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists "avatar owner delete" on storage.objects;
create policy "avatar owner delete" on storage.objects for delete to authenticated using (bucket_id='avatars' and (storage.foldername(name))[1]=auth.uid()::text);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.profiles(id,full_name)
  values(new.id,coalesce(new.raw_user_meta_data->>'full_name',''))
  on conflict(id) do nothing;
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();
